### ISSUE TITLE
Projeto top 

### ISSUE THREAD

**Issue by Rasantis** [Guiflayrom/yolnp#2]
Fala Gui, projeto top cara, parabéns, tá sensacional... Deixa eu te falar, aparentemente tem algumas dependencias que estão desatualizadas e dando conflito impossibilitando de baixar os requirements e rodar o projeto... mesmo baixando indidualmente dá alguns conflitos, entre o paddle ocr e o PyMuPDF e tem mais algumas ... aí tá meio complicado de rodar esse projeto tão topp ! Se vc conseguisse dar uma mexidinha seria de grande ajuda ! parabéns pelo projeto...

**Comment by Guiflayrom** [comment]
Opa Rasantis!!
Agradeço os elogios! O projeto publico está sim descontinuado, não tenho intenção de voltar a mexer nele tão cedo, está surgindo uma onda de pessoas e organizações querendo usar ela para fins próprios, o que literalmente rompe o artigo quinto da constituição

> Art. 5º Todos são iguais perante a lei, sem distinção de qualquer natureza, garantindo-se aos brasileiros e aos estrangeiros residentes no País a inviolabilidade do direito à vida, à liberdade, à igualdade, à segurança e à propriedade, nos termos seguintes:
> X - são invioláveis a intimidade, a vida privada, a honra e a imagem das pessoas, assegurado o direito a indenização pelo dano material ou moral decorrente de sua violação;

Literalmente prefeitos me contatando no LinkedIn querendo usar a ferramenta. Tenho uma versão atualizada e totalmente modificada com MUITO mais features, e que segue o protocolo da LGPD e que me certifico que será usada apenas em locais privados.
